In [1]:
# !pip install numpy

In [2]:
import numpy as np
from numpy import nan, isnan

# Singularities

In [3]:
x = [nan, 100, 200, 300, 400, 500]
x

[nan, 100, 200, 300, 400, 500]

In [4]:
isnan(x)

array([ True, False, False, False, False, False])

In [5]:
dict(
    sum    = np.nansum(x), 
    mean   = np.nanmean(x), 
    std    = np.nanstd(x).round(1), 
    max    = np.nanmax(x), 
    median = np.nanmedian(x), 
    min    = np.nanmin(x), 
)

{'sum': 1500.0,
 'mean': 300.0,
 'std': 141.4,
 'max': 500.0,
 'median': 300.0,
 'min': 100.0}

# Generation

In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

# Instance

In [8]:
X = np.array([10,20,30,40,50,60,70,80,90])
X

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Unique Keys

In [9]:
np.unique([*['AAA','BBB','CCC','DDD'], *['CCC','DDD','EEE','FFF']])

array(['AAA', 'BBB', 'CCC', 'DDD', 'EEE', 'FFF'], dtype='<U3')

# Slice

In [9]:
X[:3], X[3:]

(array([10, 20, 30]), array([40, 50, 60, 70, 80, 90]))

In [10]:
X[:-3], X[-3:]

(array([10, 20, 30, 40, 50, 60]), array([70, 80, 90]))

# Reverse

In [11]:
X[::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

# Filter

In [12]:
cond = (30 < X) & (X < 70)
cond

array([False, False, False,  True,  True,  True, False, False, False])

In [13]:
X[cond]

array([40, 50, 60])

# Operations

In [14]:
X + 2

array([12, 22, 32, 42, 52, 62, 72, 82, 92])

In [15]:
X * 2

array([ 20,  40,  60,  80, 100, 120, 140, 160, 180])

In [16]:
X ** 2

array([ 100,  400,  900, 1600, 2500, 3600, 4900, 6400, 8100])

# Functions

In [17]:
np.exp([1,2,3,4,5]).round(3)

array([  2.718,   7.389,  20.086,  54.598, 148.413])

In [18]:
np.log2([64, 128, 256, 512, 1024])

array([ 6.,  7.,  8.,  9., 10.])

# Totals

In [19]:
X.sum(), X.max(), X.mean(), X.min(), X.std()

(450, 90, 50.0, 10, 25.81988897471611)

# Cumulative

In [20]:
X.cumsum()

array([ 10,  30,  60, 100, 150, 210, 280, 360, 450])

In [21]:
Y = (1+X/100)
Y = Y.cumprod()
Y = Y *100-100
Y = Y.round(1)
Y

array([  10. ,   32. ,   71.6,  140.2,  260.4,  476.6,  880.2, 1664.3,
       3252.2])

# Loopings

In [22]:
for i, x in enumerate(X):
    print(i, x)

0 10
1 20
2 30
3 40
4 50
5 60
6 70
7 80
8 90


In [23]:
[(i,x) for (i,x) in enumerate(X)]

[(0, 10),
 (1, 20),
 (2, 30),
 (3, 40),
 (4, 50),
 (5, 60),
 (6, 70),
 (7, 80),
 (8, 90)]

In [24]:
[sum(X[None:i+1]) for (i,x) in enumerate(X)]

[10, 30, 60, 100, 150, 210, 280, 360, 450]